@startuml

actor HR as "HR Advisor"

rectangle Database

rectangle "HR System" {
    usecase UC4 as "Get salaries by role"
    usecase UC5 as "Get salaries by department"
    usecase UC6 as "Get all employee salaries"
    usecase UC7 as "View employee details"
    usecase UC8 as "Update employee details"
    usecase UC9 as "Add new employee"
    usecase UC10 as "Delete employee details"
    usecase UCa as "Print salaries"

    UC4 ..> UCa : include
    UC5 ..> UCa : include
    UC6 ..> UCa : include

    UC4 --> Database
    UC5 --> Database
    UC6 --> Database
    UC7 --> Database
    UC8 --> Database
    UC9 --> Database
    UC10 --> Database
}

@enduml